library(Seurat)
library(data.table)

conds = read.csv(snakemake@params[['conds']])$conditions
proj  = unique(read.csv(snakemake@params[['conds']])$project)

raw_counts = as.data.frame(fread(file=snakemake@input[['raw_counts']]))
row.names(raw_counts) = raw_counts$Cell_Index
raw_counts = raw_counts[, -1]
adt_index  = grep('-adt', colnames(raw_counts))

##************************************Starting STEP1: Data preprocessing************************************
rna_counts = raw_counts[, -adt_index]
adt_counts = raw_counts[, adt_index]


# load filtered 10x data (generated by cellranger) into a Seurat list
seur_list = lapply(1:length(conds), function(i) {
  cells_select = grep(paste0('^', conds[i]), row.names(raw_counts), value=T)   # select rows of this condition
  print(paste(conds[i], 'has', length(cells_select), 'cells'))
  seur_temp          = CreateSeuratObject(counts=t(rna_counts[cells_select, ]), project=proj, 
                                          min.cells=3, min.features=200, names.delim="-")
  seur_temp$pc_mito  = PercentageFeatureSet(object=seur_temp, pattern="^mt-")
  seur_temp$pc_ribo  = PercentageFeatureSet(object=seur_temp, pattern="^Rp[sl]")
  seur_temp$log10GenesPerUMI = log10(seur_temp$nFeature_RNA) / log10(seur_temp$nCount_RNA) # UMIs nb per gene for each cell to metadata
  metadata            = seur_temp@meta.data
  metadata$cells      = rownames(metadata)
  metadata$sample     = metadata$orig.ident                                
  seur_temp@meta.data = metadata
  
  cells_select       = metadata$cells
  seur_temp[['ADT']] = CreateAssayObject(counts=t(adt_counts[cells_select, ]))

  seur_temp
})
names(seur_list) = conds
##************************************End STEP1: Data preprocessing************************************


##************************************Start STEP2: Quality control************************************
# Create a merged Seurat object
merged_seur           = merge(x=seur_list[[1]], y=c(seur_list[[2]]))#, add.cell.ids=NULL)
metadata              = merged_seur@meta.data
metadata$orig.ident   = factor(metadata$orig.ident, levels=conds)  # keep to render plot in WT, KO order 
metadata$sample       = metadata$orig.ident                        # keep to render plot in WT, KO order 
merged_seur@meta.data = metadata
print(paste0("Merging '", paste(conds, collapse=', '), "' done! Dimensions of merged seurat object: ", nrow(merged_seur), ' genes, ', ncol(merged_seur), ' cells'))

saveRDS(merged_seur, file=snakemake@output[['seur']])